<a href="https://colab.research.google.com/github/Trantracy/100_Numpy_exercises/blob/master/Tran_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

In [0]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [0]:
print(64*zero.size)

640


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [0]:
zero10 = np.zeros(10)
zero10[4] = 1
zero10

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [0]:
range10 = np.arange(10,50)
range10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [0]:
range10[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [0]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [0]:
a = [1,2,0,0,4,0] 
b = [i for i in range(len(a)) if a[i] != 0]
b

[0, 1, 4]

In [0]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [0]:
np.random.random((3,3,3))

array([[[0.62376534, 0.57220872, 0.2591295 ],
        [0.517119  , 0.31764536, 0.31319802],
        [0.61597618, 0.41026439, 0.37358223]],

       [[0.6318349 , 0.81977905, 0.52839274],
        [0.6298287 , 0.54085866, 0.05020298],
        [0.08622657, 0.21394708, 0.68043635]],

       [[0.40381211, 0.02792923, 0.64773261],
        [0.42921931, 0.55439121, 0.17897699],
        [0.32069332, 0.17819451, 0.15586307]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [0]:
ram = np.random.randint(low = 10, size =(10, 10)) 

In [0]:
np.min(ram)

0

In [0]:
ram.max()

9

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [0]:
vector = np.random.randint(low = 30 , size = 30)
np.mean(vector)

17.966666666666665

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [0]:
 array = np.ones(25).reshape(5,5)
 array[1:-1,1:-1] = 0
 array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [0]:
Z = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [0]:
Z = np.diag(np.arange(1,5),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [0]:
Z = np.zeros((8,8))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
Z[1::2,::2] = 2 # Fill dòng lẻ với cột chẵn = 2
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 2., 0., 2., 0., 2., 0.]])

In [0]:
Z[::2,1::2] = 1 # Fill dòng chẵn với cột lẻ = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [2., 0., 2., 0., 2., 0., 2., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [2., 0., 2., 0., 2., 0., 2., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [0]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [0]:
np.tile((2,2),(8,4))

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [0]:
an_array = np.random.rand(5,5)
an_array
# Call numpy.linalg.norm(arr) 
# to find the normal form of an array arr. Divide an array by its norm to normalize the array.
norm = np.linalg.norm(an_array)
normal_array = an_array/norm
print(normal_array)

[[0.11859609 0.06263696 0.21681516 0.29241994 0.14512935]
 [0.05664303 0.1347176  0.30989709 0.09214992 0.14436253]
 [0.28486503 0.10169071 0.30101666 0.13424919 0.30013874]
 [0.04747609 0.01439413 0.32780419 0.05304675 0.18118708]
 [0.07965868 0.27937277 0.2309247  0.32760643 0.02987749]]


In [0]:
np.sum(normal_array, axis = 0)

array([0.58723891, 0.59281216, 1.3864578 , 0.89947223, 0.8006952 ])

In [0]:
a = np.arange(0,27,3).reshape(3,3)
# normalize each row such that its magnitude is one 
#(i.e. a row's unit length is one or the sum of the square of each element in a row is one):
result = a / np.linalg.norm(a, axis=-1)[:, np.newaxis] 
print(a)
print()
print(result)
np.sum(result, axis = 1)


[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]

[[0.         0.4472136  0.89442719]
 [0.42426407 0.56568542 0.70710678]
 [0.49153915 0.57346234 0.65538554]]


array([1.34164079, 1.69705627, 1.72038703])

In [0]:
# row_sums[:, numpy.newaxis] reshapes row_sums from being (3,) to being (3, 1)
# When you do a / b, a and b are broadcast against each other.
row_sums = a.sum(axis=1)
new_matrix = a / row_sums[:, np.newaxis]
print (new_matrix )
print(np.sum(new_matrix, axis = 1, keepdims = True))

[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]
[[1.]
 [1.]
 [1.]]


In [0]:
# keepdims=True to keep the singleton column dimension, which you can then broadcast along without having to use np.newaxis
row_sums = a.sum(axis=1, keepdims=True)
new_matrix = a / row_sums
new_matrix

print(np.sum(new_matrix, axis = 1, keepdims = True))

[[1.]
 [1.]
 [1.]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [0]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

In [0]:
Z = np.ones((5,3)) @ np.ones((3,2))
Z

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [0]:
Z = np.arange(3,11)
Z[(3 < Z) & (Z < 8)] =Z[(3 < Z) & (Z < 8)] * -1
Z

array([ 3, -4, -5, -6, -7,  8,  9, 10])

In [0]:
a = np.arange(3,11)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
a[1:5] = a[1:5]*-1
a

array([ 3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [0]:
i=0
sum =0
for i in range(5):
  sum=sum+i
print(sum)


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [0]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

#### 29. How to round away from zero a float array ? (★☆☆)

In [0]:
Z= np.random.uniform(-10,+10,10)
Z

array([ 1.99148878, -8.30342386, -0.16159272, -1.97973808, -8.40918182,
        6.21064511,  2.28573261,  7.51045403, -4.30051302,  3.54182281])

In [0]:
np.ceil(np.abs(Z))

array([2., 9., 1., 2., 9., 7., 3., 8., 5., 4.])

In [0]:
np.copysign(np.ceil(np.abs(Z)), Z)

array([ 2., -9., -1., -2., -9.,  7.,  3.,  8., -5.,  4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [0]:
a = np.random.randint(0,10,10)
a

array([0, 2, 3, 2, 1, 4, 8, 0, 5, 8])

In [0]:
b = np.random.randint(0,10,10)
b

array([3, 7, 1, 9, 6, 5, 1, 1, 7, 3])

In [0]:
np.intersect1d(a,b)

array([1, 3, 5])

In [0]:
set([i for i in a if i in b])

{1, 3, 5}

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [0]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [0]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(-1, 'D')
print("Tomorrow: ",tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [0]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [0]:
A= np.ones(3)
A


array([1., 1., 1.])

In [0]:
B = np.ones(3)*2
B

array([2., 2., 2.])

In [0]:
A = np.ones(3)
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

In [0]:
(A+B)*(-A/2)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [0]:
np.random.uniform(0,10,10)

In [0]:
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [0]:
np.tile(np.array([0,1,2,3,4]), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [0]:
np.array([[0,1,2,3,4]]*5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [0]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [0]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [0]:
np.random.uniform(0,1,10)

In [0]:
np.linspace(0,1,11)[1:]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [0]:
z = np.random.uniform(0,1,10)
z.sort()
z

array([0.16427843, 0.26731871, 0.34959771, 0.39058011, 0.54672032,
       0.62224887, 0.7300599 , 0.74730415, 0.86548907, 0.96893996])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [0]:
%timeit
Z = np.arange(10)
np.add.reduce(Z)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [0]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

In [0]:
A == B


In [0]:
equal = np.allclose(A,B)
print(equal)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [0]:
q= np.random.random((10,2))
q

array([[0.61274485, 0.26102686],
       [0.85171787, 0.65869463],
       [0.45847151, 0.80772079],
       [0.7686333 , 0.03982065],
       [0.30300716, 0.01704444],
       [0.80239809, 0.36877911],
       [0.92970726, 0.12693472],
       [0.21627953, 0.95655592],
       [0.15455451, 0.40913447],
       [0.61907819, 0.7238091 ]])

In [0]:
X,Y = q[:,0], q[:,1]

In [0]:
X

array([0.61274485, 0.85171787, 0.45847151, 0.7686333 , 0.30300716,
       0.80239809, 0.92970726, 0.21627953, 0.15455451, 0.61907819])

In [0]:
Y

array([0.26102686, 0.65869463, 0.80772079, 0.03982065, 0.01704444,
       0.36877911, 0.12693472, 0.95655592, 0.40913447, 0.7238091 ])

In [0]:

R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print()
print(T)

[0.66602648 1.07670885 0.92876746 0.7696641  0.30348616 0.88308591
 0.93833257 0.98070183 0.43735353 0.95244812]

[0.40271397 0.65829207 1.05453252 0.0517608  0.05619173 0.43080541
 0.13569293 1.34843291 1.20960841 0.86322997]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [0]:
z = np.random.random(10)
z

array([0.30702731, 0.06138048, 0.24562552, 0.40437624, 0.98606397,
       0.60243573, 0.83655178, 0.70748561, 0.9810492 , 0.95929738])

In [0]:
z[np.argmax(z)] = 0
z


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [0]:
np.zeros((5,5), [('x',float),('y',float)]) # list of tuple

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [0]:
Z['x']

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [0]:
Z['y']

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25, 0.25, 0.25],
       [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  , 1.  , 1.  ]])

In [0]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x']= np.meshgrid(np.linspace(0,1,5))
# Z['y']= np.meshgrid(np.linspace(0,1,5))
Z

array([[(0.  , 0.), (0.25, 0.), (0.5 , 0.), (0.75, 0.), (1.  , 0.)],
       [(0.  , 0.), (0.25, 0.), (0.5 , 0.), (0.75, 0.), (1.  , 0.)],
       [(0.  , 0.), (0.25, 0.), (0.5 , 0.), (0.75, 0.), (1.  , 0.)],
       [(0.  , 0.), (0.25, 0.), (0.5 , 0.), (0.75, 0.), (1.  , 0.)],
       [(0.  , 0.), (0.25, 0.), (0.5 , 0.), (0.75, 0.), (1.  , 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [0]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y']= np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [0]:
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [0]:

x = np.arange(90).reshape((-1,3,3))
print("Original array:")
print(x)


In [0]:
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
# index = (np.abs(x-a)).argmin()
# print(x[index])
x.flat[np.abs(x - a).argmin()]

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [0]:
Z = np.arange(9).reshape(3,3)
Z

In [0]:
for index, value in np.ndenumerate(Z):
    print(index, value)

In [0]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

In [0]:
np.ndindex(Z.shape)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

In [0]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print()
print(Z[Z[:,1].argsort()])

In [0]:
arr2D = np.array([[11, 12, 13, 22], [21, 7, 23, 14], [31, 10, 33, 7]])
 
print('2D Numpy Array')
print(arr2D)

In [0]:
arr2D[:,1].argsort()

In [0]:
arr2D[1]

In [0]:
sortedArr = arr2D[arr2D[:,1].argsort()]
 
print('Sorted 2D Numpy Array')
print(sortedArr)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [0]:
Z = np.random.randint(0,3,(3,10))
Z

In [0]:
print((~Z.any(axis=0)).any())

In [0]:
(np.any(Z==0,axis=0)).any()

#### 61. Find the nearest value from a given value in an array (★★☆)

In [0]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [0]:
A = np.random.randint(0,10,(2,3,4,4))
A

In [0]:
A.shape[:2]+(-1,0)

In [0]:
abc = A.reshape(A.shape[:-2] + (-1,))
abc

In [0]:
abc.sum(axis=-1)


In [0]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

In [0]:
a = np.arange(27).reshape(3,3,3)

# sum all layers
result = a.reshape((a.shape[0], a.shape[1]*a.shape[2])).sum(axis=1)
result

In [0]:
a.reshape((a.shape[0], a.shape[1]*a.shape[2]))

In [0]:
a = np.arange(27).reshape(3,3,3)
a

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [0]:
A = np.random.uniform(0,1,(5,5))
A

In [0]:

B = np.random.uniform(0,1,(5,5))
B

In [0]:
np.diag(np.dot(A, B))


In [0]:
np.sum(A * B.T, axis=1)

In [0]:
A * B.T

In [0]:
dot(A, B)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [0]:
Z = np.array([1,2,3,4,5])


In [0]:
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

In [0]:
Z0=np.zeros(len(Z) + (len(Z)-1)*3)
Z0

In [0]:
Z0[::nz+1] =Z
len(Z0)

In [0]:
Z0[::nz+1]

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [0]:
A = np.ones((5,5,3))
A

In [0]:
B = 2*np.ones((5,5))
B

In [0]:
B[:,:, None]

In [0]:
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [0]:
A = np.arange(25).reshape(5,5)
A

In [0]:
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [0]:
A = np.array([[1,3,7],[2,8,3],[7,8,1]])
A

In [0]:
np.linalg.matrix_rank(A)

#### 83. How to find the most frequent value in an array?

In [0]:
Z = np.random.randint(0,10,10)
Z

In [0]:
np.bincount(Z).argmax()

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [0]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [0]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
Z[np.argsort(Z)[-5:]]

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [0]:
a = np.ones((1, 2, 3))
a

In [0]:
x = np.array([[[4, 2, 1],
       [0, 2, 1],
       [1, 2, 0],
       [3, 3, 4]]])
x.shape

In [0]:
x = np.array([[[4, 2, 1],
       [0, 2, 1],
       [1, 2, 0],
       [3, 3, 4]]])
np.transpose(x, (1, 0, 2))

In [0]:
x = np.array([1,2,3])
y = np.array([4,5])
x


In [0]:
np.tile(x, len(y))


In [0]:
np.repeat(y, len(x))

In [0]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5])
result = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
print(result)

In [0]:
np.transpose([1, 2, 3, 1, 2, 3],[4, 4, 4, 5, 5, 5])

In [0]:
x = numpy.array([1,2,3])
y = numpy.array([4,5])
z = numpy.array([6, 7])
a = [[x0, y0, z0] for x0 in x for y0 in y for z0 in z ]
np.array(a)

In [0]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [0]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [0]:
A = np.random.randint(0,5,(8,3))
A 

In [0]:
B = np.random.randint(0,5,(2,2))
B

In [0]:
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [0]:
nums= np.array([[4, 2, 1],
       [0, 2, 1],
       [1, 2, 0],
       [3, 3, 4],
       [1, 4, 1],
       [1, 4, 1],
       [1, 2, 4],
       [1, 2, 0],
       [4, 2, 1],
       [4, 2, 4]])
nums

In [0]:
new_nums = np.logical_and.reduce(nums[:,1:] == nums[:,:-1], axis=1)
result = nums[~new_nums]
print("\nRows with unequal values:")
print(result)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [0]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
print(B.shape)
print(B)

In [0]:
v= np.array([1, 5, 3])
C = np.zeros((v.shape[0], v.max()))
C

In [0]:
C[np.arange(v.shape[0]), v.T-1] = 1
C

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [0]:
a = np.array([[1, 1, 1, 0, 0, 0],
              [0, 1, 1, 1, 0, 0],
              [0, 1, 1, 1, 0, 0],
              [1, 1, 1, 0, 0, 0],
              [1, 1, 1, 1, 1, 0]])

In [0]:
np.unique(a, axis=0)


In [0]:
np.vstack({tuple(row) for row in a})

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)